# -*- coding: utf-8 -*-
"""cripto-lab2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zmsJpQ_ghQSXQtb25x-NbbC_Y8xwZp7v

#Instalación
"""

!pip install selenium
!apt-get update # to update ubuntu to correctly run apt install
!apt install chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin

"""#Hito II"""

from selenium.webdriver.common.by import By
import csv
import sys
sys.path.insert(0,'/usr/lib/chromium-browser/chromedriver')
from selenium import webdriver
from time import sleep
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')

cuentas = []

with open('cuentas.csv', newline='') as csvfile:
  spamreader = csv.reader(csvfile, delimiter=' ', quotechar='|')
  for row in spamreader:
    cuentas.append(row[0].split(','))

for i in range(len(cuentas)):
  wd = webdriver.Chrome('chromedriver', options=chrome_options)
  wd.get("https://www.netflix.com/cl-en/login")
  sleep(1)
  wd.find_element(By.ID, 'id_userLoginId').send_keys(cuentas[i][0])
  wd.find_element(By.ID, 'id_password').send_keys(cuentas[i][1])
  wd.find_element(By.XPATH, value='//*[@id="appMountPoint"]/div/div[3]/div/div/div[1]/form/button').click()
  sleep(1)
  ss = 'Hito2-Screenshot'+str(i).zfill(2)+'.png'
  wd.save_screenshot(ss)

"""#Hito III

##Credenciales
"""

import json
import sys
sys.path.insert(0,'/usr/lib/chromium-browser/chromedriver')
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common import action_chains

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
chrome_options.add_argument("--window-size=1920,1920")
wd = webdriver.Chrome('chromedriver', options=chrome_options)

wd.get('https://www.1secmail.com/api/v1/?action=genRandomMailbox')
correo = json.loads(wd.find_element(By.TAG_NAME,'body').text)[0]

nombre = 'nombre'
apellido = 'apellido'
contrasena = 'abc123'
print(correo)

"""##Página chilena https://pcnitro.cl/

###Registro
"""

import json
import sys
sys.path.insert(0,'/usr/lib/chromium-browser/chromedriver')
from selenium import webdriver
from time import sleep
from selenium.webdriver.common.by import By
from selenium.webdriver.common import action_chains

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
chrome_options.add_argument("--window-size=1920,1920")
wd = webdriver.Chrome('chromedriver', options=chrome_options)


wd.get("https://pcnitro.cl/iniciar-sesion?create_account=1")
sleep(2)
wd.find_element(By.XPATH, value='/html/body/main/div[2]/div/div/div/div[2]/div/div[1]/div/section/form/div/div[1]/div[1]/label[1]/span/input').click()
wd.find_element(By.XPATH, value='/html/body/main/div[2]/div/div/div/div[2]/div/div[1]/div/section/form/div/div[2]/div[1]/input').send_keys(nombre)
wd.find_element(By.XPATH, value='/html/body/main/div[2]/div/div/div/div[2]/div/div[1]/div/section/form/div/div[3]/div[1]/input').send_keys(apellido)
wd.find_element(By.XPATH, value='/html/body/main/div[2]/div/div/div/div[2]/div/div[1]/div/section/form/div/div[4]/div[1]/input').send_keys(correo)
wd.find_element(By.XPATH, value='/html/body/main/div[2]/div/div/div/div[2]/div/div[1]/div/section/form/div/div[5]/div[1]/div/input').send_keys(contrasena)
checkbox = wd.find_element(By.XPATH, value='//*[@id="customer_privacy"]')
action = action_chains.ActionChains(wd)
action.move_to_element_with_offset(checkbox, 1, 1).click().perform()
checkbox = wd.find_element(By.XPATH, value='//*[@id="psgdpr"]')
action = action_chains.ActionChains(wd)
action.move_to_element_with_offset(checkbox, 1, 1).click().perform()
wd.save_screenshot('Hito3a-Screenshot00.png')
wd.find_element(By.XPATH, value='/html/body/main/div[2]/div/div/div/div[2]/div/div[1]/div/section/form/footer/button').click()
sleep(2)
wd.save_screenshot('Hito3a-Screenshot01.png')

"""###Inicio de sesión"""

import sys
sys.path.insert(0,'/usr/lib/chromium-browser/chromedriver')
from selenium import webdriver
from time import sleep
from selenium.webdriver.common import action_chains

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
chrome_options.add_argument("--window-size=1920,1920")
wd = webdriver.Chrome('chromedriver', options=chrome_options)
wd.get("https://pcnitro.cl/iniciar-sesion")
sleep(2)
wd.find_element(By.XPATH, value='/html/body/main/div[2]/div/div/div/div[2]/div/div[1]/div/div[1]/form/div/div[1]/div[1]/input').send_keys(correo)
wd.find_element(By.XPATH, value='/html/body/main/div[2]/div/div/div/div[2]/div/div[1]/div/div[1]/form/div/div[2]/div[1]/div/input').send_keys(contrasena)
wd.save_screenshot('Hito3a-Screenshot02.png')
wd.find_element(By.XPATH, value='//*[@id="submit-login"]').click()
sleep(2)
wd.save_screenshot('Hito3a-Screenshot03.png')

"""###Restablecimiento de contraseña (sin login)"""

import sys
sys.path.insert(0,'/usr/lib/chromium-browser/chromedriver')
from selenium import webdriver
from time import sleep
from selenium.webdriver.common import action_chains

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
chrome_options.add_argument("--window-size=1920,1920")
wd = webdriver.Chrome('chromedriver', options=chrome_options)
wd.get("https://pcnitro.cl/recuperar-contrase%C3%B1a")
sleep(2)
wd.find_element(By.XPATH, value='//*[@id="email"]').send_keys(correo)
wd.save_screenshot('Hito3a-Screenshot04.png')
wd.find_element(By.XPATH, value='//*[@id="content"]/form/section/div/button[1]').click()
sleep(2)
wd.save_screenshot('Hito3a-Screenshot05.png')

import json
sys.path.insert(0,'/usr/lib/chromium-browser/chromedriver')
from selenium import webdriver
from selenium.webdriver.common import action_chains

usuario = correo.split('@')[0]
dominio = correo.split('@')[1]

url = 'https://www.1secmail.com/api/v1/?action=getMessages&login=' + usuario + '&domain=' + dominio
wd.get(url)
mensajes = json.loads(wd.find_element(By.TAG_NAME,'body').text)

for i in mensajes:
  if i['subject'] == '[PCNITRO] Confirmación de contraseña':
    url = 'https://www.1secmail.com/api/v1/?action=readMessage&login=' + usuario + '&domain=' + dominio + '&id=' + str(i['id'])
    wd.get(url)
    break
index = json.loads(wd.find_element(By.TAG_NAME,'body').text)['body'].find('enlace')
url = json.loads(wd.find_element(By.TAG_NAME,'body').text)['body'][index+17:index+200].split('"')[0]
wd.get(url)
sleep(2)
wd.save_screenshot('Hito3a-Screenshot06.png')

nuevaContrasena = '321321'

wd.find_element(By.XPATH, value='//*[@id="content"]/form/section/div[2]/div[1]/div/input').send_keys(nuevaContrasena)
wd.find_element(By.XPATH, value='//*[@id="content"]/form/section/div[2]/div[2]/div/input').send_keys(nuevaContrasena)
sleep(1)
wd.save_screenshot('Hito3a-Screenshot07.png')
wd.find_element(By.XPATH, value='//*[@id="content"]/form/section/div[2]/div[3]/div/button').click()
sleep(3)
wd.save_screenshot('Hito3a-Screenshot08.png')

"""###Modificación de contraseña (con login)"""

import sys
sys.path.insert(0,'/usr/lib/chromium-browser/chromedriver')
from selenium import webdriver
from time import sleep
from selenium.webdriver.common import action_chains


contrasena = '321321'
nuevacontrasena2 = '123asd'


chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
chrome_options.add_argument("--window-size=1920,1920")
wd = webdriver.Chrome('chromedriver', options=chrome_options)
wd.get("https://pcnitro.cl/iniciar-sesion")
sleep(3)
wd.find_element(By.XPATH, value='/html/body/main/div[2]/div/div/div/div[2]/div/div[1]/div/div[1]/form/div/div[1]/div[1]/input').send_keys(correo)
wd.find_element(By.XPATH, value='/html/body/main/div[2]/div/div/div/div[2]/div/div[1]/div/div[1]/form/div/div[2]/div[1]/div/input').send_keys(contrasena)
wd.find_element(By.XPATH, value='//*[@id="submit-login"]').click()
sleep(3)
wd.get('https://pcnitro.cl/datos-personales')
sleep(3)
wd.save_screenshot('Hito3a-Screenshot09.png')
wd.find_element(By.XPATH, value='/html/body/main/div[2]/div/div/div/div[2]/div/div[1]/section/form/div/div[5]/div[1]/div/input').send_keys(contrasena)
wd.find_element(By.XPATH, value='/html/body/main/div[2]/div/div/div/div[2]/div/div[1]/section/form/div/div[6]/div[1]/div/input').send_keys(nuevacontrasena2)
wd.find_element(By.XPATH, value='/html/body/main/div[2]/div/div/div/div[2]/div/div[1]/section/form/div/div[5]/div[1]/div/span/button').click()
wd.find_element(By.XPATH, value='/html/body/main/div[2]/div/div/div/div[2]/div/div[1]/section/form/div/div[6]/div[1]/div/span/button').click()
checkbox = wd.find_element(By.XPATH, value='//*[@id="customer_privacy"]')
action = action_chains.ActionChains(wd)
action.move_to_element_with_offset(checkbox, 1, 1).click().perform()
checkbox = wd.find_element(By.XPATH, value='//*[@id="psgdpr"]')
action = action_chains.ActionChains(wd)
action.move_to_element_with_offset(checkbox, 1, 1).click().perform()
sleep(1)
wd.save_screenshot('Hito3a-Screenshot10.png')
wd.find_element(By.XPATH, value='/html/body/main/div[2]/div/div/div/div[2]/div/div[1]/section/form/footer/button').click()
sleep(3)
wd.save_screenshot('Hito3a-Screenshot11.png')

"""##Credenciales"""

import json
import sys
sys.path.insert(0,'/usr/lib/chromium-browser/chromedriver')
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common import action_chains

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
chrome_options.add_argument("--window-size=1920,1920")
wd = webdriver.Chrome('chromedriver', options=chrome_options)

wd.get('https://www.1secmail.com/api/v1/?action=genRandomMailbox')
correo = json.loads(wd.find_element(By.TAG_NAME,'body').text)[0]

nombre = 'nombre'
apellido = 'apellido'
contrasena = 'abc123'
print(correo)

"""##Página europea https://www.neobyte.es/

###Registro
"""

import json
import sys
sys.path.insert(0,'/usr/lib/chromium-browser/chromedriver')
from selenium import webdriver
from time import sleep
from selenium.webdriver.common.by import By
from selenium.webdriver.common import action_chains

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
chrome_options.add_argument("--window-size=1920,1920")
wd = webdriver.Chrome('chromedriver', options=chrome_options)


wd.get("https://www.neobyte.es/inicio-sesion?create_account=1")
sleep(2)
wd.find_element(By.XPATH, value='//*[@id="customer-form"]/section/div[1]/div[1]/label[1]/span/input').click()
wd.find_element(By.XPATH, value='//*[@id="customer-form"]/section/div[2]/div[1]/input').send_keys(nombre)
wd.find_element(By.XPATH, value='//*[@id="customer-form"]/section/div[3]/div[1]/input').send_keys(apellido)
wd.find_element(By.XPATH, value='//*[@id="customer-form"]/section/div[4]/div[1]/input').send_keys(correo)
wd.find_element(By.XPATH, value='//*[@id="customer-form"]/section/div[5]/div[1]/div/input').send_keys(contrasena)
checkbox = wd.find_element(By.XPATH, value='//*[@id="ff_customer_privacy"]')
action = action_chains.ActionChains(wd)
action.move_to_element_with_offset(checkbox, 1, 1).click().perform()
checkbox = wd.find_element(By.XPATH, value='//*[@id="ff_psgdpr"]')
action = action_chains.ActionChains(wd)
action.move_to_element_with_offset(checkbox, 1, 1).click().perform()
wd.save_screenshot('Hito3b-Screenshot00.png')
wd.find_element(By.XPATH, value='//*[@id="customer-form"]/footer/button').click()
sleep(2)
wd.save_screenshot('Hito3b-Screenshot01.png')

"""###Inicio de sesión"""

import sys
sys.path.insert(0,'/usr/lib/chromium-browser/chromedriver')
from selenium import webdriver
from time import sleep
from selenium.webdriver.common import action_chains

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
chrome_options.add_argument("--window-size=1920,1920")
wd = webdriver.Chrome('chromedriver', options=chrome_options)
wd.get("https://www.neobyte.es/inicio-sesion?back=my-account")
sleep(2)
wd.find_element(By.XPATH, value='//*[@id="login-form"]/section/div[1]/div[1]/input').send_keys(correo)
wd.find_element(By.XPATH, value='//*[@id="login-form"]/section/div[2]/div[1]/div/input').send_keys(contrasena)
wd.save_screenshot('Hito3b-Screenshot02.png')
wd.find_element(By.XPATH, value='//*[@id="submit-login"]').click()
sleep(2)
wd.save_screenshot('Hito3b-Screenshot03.png')

"""###Restablecimiento de contraseña (sin login)"""

import sys
sys.path.insert(0,'/usr/lib/chromium-browser/chromedriver')
from selenium import webdriver
from time import sleep
from selenium.webdriver.common import action_chains

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
chrome_options.add_argument("--window-size=1920,1920")
wd = webdriver.Chrome('chromedriver', options=chrome_options)
wd.get("https://www.neobyte.es/recuperacion")
sleep(2)
wd.find_element(By.XPATH, value='//*[@id="email"]').send_keys(correo)
wd.save_screenshot('Hito3b-Screenshot04.png')
wd.find_element(By.XPATH, value='//*[@id="content"]/section/form/button').click()
sleep(2)
wd.save_screenshot('Hito3b-Screenshot05.png')

import json
sys.path.insert(0,'/usr/lib/chromium-browser/chromedriver')
from selenium import webdriver
from selenium.webdriver.common import action_chains

usuario = correo.split('@')[0]
dominio = correo.split('@')[1]

url = 'https://www.1secmail.com/api/v1/?action=getMessages&login=' + usuario + '&domain=' + dominio
wd.get(url)
mensajes = json.loads(wd.find_element(By.TAG_NAME,'body').text)

for i in mensajes:
  if i['subject'] == '[NEOBYTE] Confirmación de contraseña':
    url = 'https://www.1secmail.com/api/v1/?action=readMessage&login=' + usuario + '&domain=' + dominio + '&id=' + str(i['id'])
    wd.get(url)
    break
index = json.loads(wd.find_element(By.TAG_NAME,'body').text)['body'].find('enlace')
url = json.loads(wd.find_element(By.TAG_NAME,'body').text)['body'][index+17:index+200].split('"')[0].replace('amp;','')

wd.get(url)
sleep(2)
wd.save_screenshot('Hito3b-Screenshot06.png')

nuevaContrasena = '321321'

wd.find_element(By.XPATH, value='//*[@id="content"]/form/section/div[2]/div[1]/div/input').send_keys(nuevaContrasena)
wd.find_element(By.XPATH, value='//*[@id="content"]/form/section/div[2]/div[2]/div/input').send_keys(nuevaContrasena)
sleep(1)
wd.save_screenshot('Hito3b-Screenshot07.png')
wd.find_element(By.XPATH, value='//*[@id="content"]/form/section/div[2]/div[3]/div/button').click()
sleep(3)
wd.save_screenshot('Hito3b-Screenshot08.png')

"""###Modificación de contraseña (con login)"""

import sys
sys.path.insert(0,'/usr/lib/chromium-browser/chromedriver')
from selenium import webdriver
from time import sleep
from selenium.webdriver.common import action_chains


contrasena = '321321'
nuevacontrasena2 = '123456'


chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
chrome_options.add_argument("--window-size=1920,1920")
wd = webdriver.Chrome('chromedriver', options=chrome_options)
wd.get("https://www.neobyte.es/inicio-sesion?back=my-account")
sleep(3)
wd.find_element(By.XPATH, value='//*[@id="login-form"]/section/div[1]/div[1]/input').send_keys(correo)
wd.find_element(By.XPATH, value='//*[@id="login-form"]/section/div[2]/div[1]/div/input').send_keys(contrasena)
wd.find_element(By.XPATH, value='//*[@id="submit-login"]').click()
sleep(3)
wd.get('https://www.neobyte.es/datos-personales')
sleep(3)
wd.save_screenshot('Hito3b-Screenshot09.png')
wd.find_element(By.XPATH, value='//*[@id="customer-form"]/section/div[5]/div[1]/div/input').send_keys(contrasena)
wd.find_element(By.XPATH, value='//*[@id="customer-form"]/section/div[6]/div[1]/div/input').send_keys(nuevacontrasena2)
wd.find_element(By.XPATH, value='//*[@id="customer-form"]/section/div[5]/div[1]/div/span/button').click()
wd.find_element(By.XPATH, value='//*[@id="customer-form"]/section/div[6]/div[1]/div/span/button').click()
checkbox = wd.find_element(By.XPATH, value='//*[@id="ff_customer_privacy"]')
action = action_chains.ActionChains(wd)
action.move_to_element_with_offset(checkbox, 1, 1).click().perform()
checkbox = wd.find_element(By.XPATH, value='//*[@id="ff_psgdpr"]')
action = action_chains.ActionChains(wd)
action.move_to_element_with_offset(checkbox, 1, 1).click().perform()
sleep(1)
wd.save_screenshot('Hito3b-Screenshot10.png')
wd.find_element(By.XPATH, value='//*[@id="customer-form"]/footer/button').click()
sleep(3)
wd.save_screenshot('Hito3b-Screenshot11.png')